### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Tejas Panchals",
  "email": "tejasPannnnnnnnnnsssschalssssss@gmail.com",
  "address": "xyzur",
  "dateOfBirth": "1995-08-08",
  "registeredDate": "2003-08-08"
}