spring.application.name=patient-service
server.port=4000

#endpoint where we can see the data from the h2 database
spring.h2.console.path=/h2-console

#Datasource configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/patientdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#spring.sql.init.mode=always

#all logging messages will get printed on the console

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer


logging.level.root=info

#Debugging kafka errors

logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG
